version: "3.9"
services:
  movie:
    environment:
      - IMDB_KEY="$IMDB_KEY"
    build: ./movie/
    ports:
      - "3200:3200"
  showtime:
    environment:
      - IMDB_KEY="$IMDB_KEY"
    build: ./showtime/
    ports:
      - "3202:3202"
  user:
    environment:
      - IMDB_KEY="$IMDB_KEY"
    build: ./user/
    ports:
      - "3203:3203"
  booking:
    environment:
      - IMDB_KEY="$IMDB_KEY"
    build: ./booking/
    ports:
      - "3201:3201"
