version: "3.9"
services:
  movie:
    environment:
      - IMDB_KEY="$IMDB_KEY"
      - MOVIE_PORT=${MOVIE_PORT}
    build: services/movie/
    ports:
      - "${MOVIE_PORT}:${MOVIE_PORT}"

  showtime:
    environment:
      - SHOWTIME_PORT=${SHOWTIME_PORT}
    build: services/showtime/
    ports:
      - "${SHOWTIME_PORT}:${SHOWTIME_PORT}"

  user:
    environment:
      - MOVIE_PORT=${MOVIE_PORT}
      - USER_PORT=${USER_PORT}
      - BOOKING_PORT=${BOOKING_PORT}
    build: services/user/
    ports:
      - "${USER_PORT}:${USER_PORT}"
    depends_on:
      - booking
      - movie

  booking:
    environment:
      - BOOKING_PORT=${BOOKING_PORT}
      - SHOWTIME_PORT=${SHOWTIME_PORT}
    build: services/booking/
    ports:
      - "${BOOKING_PORT}:${BOOKING_PORT}"
    depends_on:
      - showtime